(function(){'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const W=72,SEA=7,MINY=-18,MAXY=32,REACH=7;let world=new Map(),seedText='Nikita123',seed=1,selected=0;
const TYPES={grass:'#62bd50',dirt:'#8a5a37',stone:'#777b7e',sand:'#d8c17a',wood:'#95623a',leaves:'#3c963f',bedrock:'#30343a',water:'#3b8fc2'};
const HOT=['grass','dirt','stone','wood','leaves','sand'];
let px=36.5,pz=36.5,py=12.01,vy=0,yaw=0,pitch=-.08,onGround=true;let sx=0,sy=0,last=performance.now(),saveTimer=0;
const key=(x,y,z)=>x+'|'+y+'|'+z, get=(x,y,z)=>world.get(key(x,y,z));
function hash(n){n|=0;n=Math.imul(n^(n>>>16),0x45d9f3b);n=Math.imul(n^(n>>>16),0x45d9f3b);return (n^(n>>>16))>>>0}
function sh(t){let h=2166136261>>>0;for(let i=0;i<t.length;i++){h^=t.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rnd(x,z,o=0){return hash((x*374761393+z*668265263+seed+o*1442695041)|0)/4294967295}
function noise(x,z,scale,o=0){x*=scale;z*=scale;let x0=Math.floor(x),z0=Math.floor(z),fx=x-x0,fz=z-z0,ux=fx*fx*(3-2*fx),uz=fz*fz*(3-2*fz);let a=rnd(x0,z0,o),b=rnd(x0+1,z0,o),c=rnd(x0,z0+1,o),d=rnd(x0+1,z0+1,o);return (a+(b-a)*ux)+((c+(d-c)*ux)-(a+(b-a)*ux))*uz}
function height(x,z){let n=noise(x,z,.025,10)*.55+noise(x,z,.07,20)*.25+noise(x,z,.012,30)*.2;let h=Math.floor(SEA-2+(n-.5)*24);return Math.max(2,Math.min(MAXY-6,h))}
function biome(x,z){let t=noise(x,z,.015,80),m=noise(x,z,.018,120);if(t>.7&&m<.45)return'desert';if(m>.64)return'forest';if(t<.28)return'taiga';return'plains'}
function cave(x,y,z){if(y>height(x,z)-3||y>SEA-1)return false;return noise(x+y,z-y,.06,500)>.73&&noise(x-y,z+y,.035,700)>.5}
function gen(s){seedText=s||'1';seed=sh(seedText);world=new Map();for(let x=0;x<W;x++)for(let z=0;z<W;z++){let h=height(x,z),b=biome(x,z);for(let y=MINY;y<=h;y++){if(y===MINY){world.set(key(x,y,z),'bedrock');continue}if(cave(x,y,z))continue;let t=y===h?((h<=SEA+1||b==='desert')?'sand':'grass'):(y>=h-3?(b==='desert'?'sand':'dirt'):'stone');world.set(key(x,y,z),t)}if(h<SEA)for(let y=h+1;y<=SEA;y++)world.set(key(x,y,z),'water');let chance=b==='forest'?.055:b==='taiga'?.03:b==='plains'?.01:0;if(chance&&h>SEA+2&&rnd(x,z,900)<chance){for(let i=1;i<=4;i++)world.set(key(x,h+i,z),'wood');for(let dx=-2;dx<=2;dx++)for(let dz=-2;dz<=2;dz++)for(let dy=3;dy<=5;dy++)if(Math.abs(dx)+Math.abs(dz)<4&&rnd(x+dx,z+dz,930+dy)>.15)world.set(key(x+dx,h+dy,z+dz),'leaves')}}spawn();}
function surface(x,z){for(let y=MAXY;y>MINY;y--){let t=get(x,y,z);if(t&&t!=='water'&&t!=='wood'&&t!=='leaves')return y}return null}
function good(x,z){if(x<8||z<8||x>=W-8||z>=W-8)return false;let y=surface(x,z);if(y===null||y<SEA+3||get(x,y,z)!=='grass')return false;for(let dx=-5;dx<=5;dx++)for(let dz=-5;dz<=5;dz++)if(Math.hypot(dx,dz)<=5){let q=surface(x+dx,z+dz);if(q===null||q<=SEA+1||Math.abs(q-y)>4)return false}return !get(x,y+1,z)&&!get(x,y+2,z)}
function spawn(){for(let i=0;i<2500;i++){let x=8+Math.floor(rnd(i,seed,31)*(W-16)),z=8+Math.floor(rnd(i,seed,61)*(W-16));if(good(x,z)){let y=surface(x,z);px=x+.5;pz=z+.5;py=y+1.01;vy=0;onGround=true;return}}let x=W/2,z=W/2,y=surface(x,z)||SEA+4;px=x+.5;pz=z+.5;py=y+1.01;vy=0;onGround=true}
function solid(x,y,z){let t=get(Math.floor(x),Math.floor(y),Math.floor(z));return !!t&&t!=='water'}
function hit(x,y,z){let r=.28;for(let a=Math.floor(x-r);a<=Math.floor(x+r);a++)for(let b=Math.floor(y);b<=Math.floor(y+1.72);b++)for(let c=Math.floor(z-r);c<=Math.floor(z+r);c++)if(solid(a,b,c))return true;return false}
function move(dt){let f=Math.sin(yaw),g=Math.cos(yaw),rx=Math.cos(yaw),rz=-Math.sin(yaw);let dx=(rx*sx+f*sy)*4.8*dt,dz=(rz*sx+g*sy)*4.8*dt;let ox=px,oz=pz;px+=dx;if(hit(px,py, pz))px=ox;pz+=dz;if(hit(px,py,pz))pz=oz;vy-=20*dt;let oy=py;py+=vy*dt;if(hit(px,py,pz)){py=oy;if(vy<0)onGround=true;vy=0}else onGround=false;if(py<MINY-3)spawn()}
function project(x,y,z){let dx=x-px,dz=z-pz;let cy=Math.cos(yaw),syy=Math.sin(yaw);let X=dx*cy-dz*syy,Z=dx*syy+dz*cy;let Y=y-(py+1.55);let cp=Math.cos(pitch),sp=Math.sin(pitch);let YY=Y*cp-Z*sp,ZZ=Y*sp+Z*cp;if(ZZ<=.15)return null;let f=Math.min(canvas.width,canvas.height)*.9;return [canvas.width/2+X*f/ZZ,canvas.height/2-YY*f/ZZ,ZZ]}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);let grd=ctx.createLinearGradient(0,0,0,canvas.height);grd.addColorStop(0,'#82c9e8');grd.addColorStop(.55,'#b9e1ee');grd.addColorStop(1,'#6d8e55');ctx.fillStyle=grd;ctx.fillRect(0,0,canvas.width,canvas.height);let maxD=22,list=[];let cx=Math.floor(px),cz=Math.floor(pz);for(let x=Math.max(0,cx-maxD);x<Math.min(W,cx+maxD);x++)for(let z=Math.max(0,cz-maxD);z<Math.min(W,cz+maxD);z++){let d=Math.hypot(x-px,z-pz);if(d>maxD)continue;for(let y=MINY;y<=MAXY;y++){let t=get(x,y,z);if(!t)continue;let p=project(x+.5,y+.5,z+.5);if(p)list.push({x,y,z,t,p,d})}}list.sort((a,b)=>b.p[2]-a.p[2]);for(let b of list)cube(b);drawCross()}
function color(t){if(t==='water')return'rgba(55,145,198,.72)';return ({grass:'#62bd50',dirt:'#8a5a37',stone:'#777b7e',sand:'#d8c17a',wood:'#95623a',leaves:'#3c963f',bedrock:'#30343a'})[t]||'#777'}
function cube(b){let x=b.x,y=b.y,z=b.z,pts=[];[[0,0,0],[1,0,0],[1,1,0],[0,1,0],[0,0,1],[1,0,1],[1,1,1],[0,1,1]].forEach(q=>pts.push(project(x+q[0],y+q[1],z+q[2])));if(pts.some(p=>!p))return;let faces=[[[0,1,2,3],.92],[[1,5,6,2],.75],[[5,4,7,6],.82],[[4,0,3,7],.68],[[3,2,6,7],1.15],[[4,5,1,0],.58]];for(let [ids,shade] of faces){ctx.beginPath();ctx.moveTo(pts[ids[0]][0],pts[ids[0]][1]);for(let i=1;i<ids.length;i++)ctx.lineTo(pts[ids[i]][0],pts[ids[i]][1]);ctx.closePath();let c=color(b.t);if(c[0]==='#'){let n=parseInt(c.slice(1),16),r=Math.min(255,Math.floor((n>>16)*shade)),g=Math.min(255,Math.floor(((n>>8)&255)*shade)),bl=Math.min(255,Math.floor((n&255)*shade));c=`rgb(${r},${g},${bl})`}ctx.fillStyle=c;ctx.fill();ctx.strokeStyle='rgba(0,0,0,.08)';ctx.stroke()}}
function rayBlock(){let fx=Math.sin(yaw)*Math.cos(pitch),fy=Math.sin(pitch),fz=Math.cos(yaw)*Math.cos(pitch);let x=px,z=pz,y=py+1.55,lastCell=null;for(let d=0;d<REACH;d+=.12){let cx=Math.floor(x),cy=Math.floor(y),cz=Math.floor(z);let k=key(cx,cy,cz),t=get(cx,cy,cz);if(t&&t!=='water')return{ x:cx,y:cy,z:cz,px:lastCell?.x,py:lastCell?.y,pz:lastCell?.z,t};lastCell={x:cx,y:cy,z:cz};x+=fx*.12;y+=fy*.12;z+=fz*.12}return null}
function mine(){let h=rayBlock();if(!h)return msg('Aim at a block');if(h.t==='bedrock')return msg('Bedrock cannot be mined');world.delete(key(h.x,h.y,h.z));msg('Mined '+h.t)}
function place(){let h=rayBlock();if(!h||h.px===undefined)return msg('Aim at a block');if(get(h.px,h.py,h.pz))return;let x=h.px,y=h.py,z=h.pz;if(x<0||z<0||x>=W||z>=W||y<MINY||y>MAXY)return;if(x+1>px-.3&&x<px+.3&&z+1>pz-.3&&z<pz+.3&&y+1>py&&y<py+1.72)return msg('Too close');world.set(key(x,y,z),HOT[selected]);msg('Placed '+HOT[selected])}
function jump(){if(onGround){vy=7.2;onGround=false}}
function save(){localStorage.setItem('NikitaCraftsSave',JSON.stringify({seedText,world:[...world],p:[px,py,pz],yaw,pitch,selected}));msg('World saved')}
function load(){try{let d=JSON.parse(localStorage.getItem('NikitaCraftsSave'));if(!d)throw 0;seedText=d.seedText;seed=sh(seedText);world=new Map(d.world);[px,py,pz]=d.p; yaw=d.yaw||0;pitch=d.pitch||-.08;selected=d.selected||0;return true}catch(e){return false}}
function msg(t){let e=document.getElementById('msg');e.textContent=t;e.style.opacity=1;clearTimeout(msg.t);msg.t=setTimeout(()=>e.style.opacity=0,1000)}
function hotbar(){let e=document.getElementById('hotbar');e.innerHTML='';HOT.forEach((t,i)=>{let s=document.createElement('div');s.className='slot'+(i===selected?' sel':'');s.innerHTML='<div class="sw" style="background:'+color(t)+'"></div><small>'+(i+1)+'</small>';s.onpointerdown=e=>{e.stopPropagation();selected=i;hotbar()};e.appendChild(s)})}
function resize(){let d=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.floor(innerWidth*d);canvas.height=Math.floor(innerHeight*d);canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px'}
function setup(){let joy=document.getElementById('joy'),knob=joy.querySelector('i'),active=false,id=null;function reset(){active=false;id=null;sx=sy=0;knob.style.transform='translate(0,0)'}function upd(e){let r=joy.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),m=Math.hypot(dx,dy),rad=47;if(m>rad){dx=dx/m*rad;dy=dy/m*rad}knob.style.transform=`translate(${dx}px,${dy}px)`;sx=dx/rad;sy=-dy/rad}joy.onpointerdown=e=>{active=true;id=e.pointerId;joy.setPointerCapture(id);upd(e)};joy.onpointermove=e=>{if(active&&e.pointerId===id)upd(e)};joy.onpointerup=reset;joy.onpointercancel=reset;
let look=document.getElementById('look'),lid=null,lx=0,ly=0;look.onpointerdown=e=>{lid=e.pointerId;look.setPointerCapture(lid);lx=e.clientX;ly=e.clientY};look.onpointermove=e=>{if(e.pointerId!==lid)return;let dx=e.clientX-lx,dy=e.clientY-ly;yaw-=dx*.006;pitch-=dy*.005;pitch=Math.max(-1.2,Math.min(1.2,pitch));lx=e.clientX;ly=e.clientY};look.onpointerup=()=>lid=null;look.onpointercancel=()=>lid=null;
['mine','place','jump'].forEach(id=>{document.getElementById(id).onpointerdown=e=>e.stopPropagation()});document.getElementById('mine').onpointerup=mine;document.getElementById('place').onpointerup=place;document.getElementById('jump').onpointerup=jump;
document.getElementById('new').onclick=()=>{gen(document.getElementById('seed').value.trim()||String(Date.now()));localStorage.removeItem('NikitaCraftsSave');startGame()};document.getElementById('cont').onclick=()=>{if(!load())gen(document.getElementById('seed').value.trim()||'Nikita123');startGame()};document.getElementById('save').onclick=save;document.getElementById('menuBtn').onclick=()=>{save();document.getElementById('hud').hidden=true;document.getElementById('menu').style.display='flex'};
window.onkeydown=e=>{if(e.key>='1'&&e.key<='6'){selected=+e.key-1;hotbar()}if(e.code==='KeyW')sy=1;if(e.code==='KeyS')sy=-1;if(e.code==='KeyA')sx=-1;if(e.code==='KeyD')sx=1;if(e.code==='Space')jump();if(e.code==='KeyF')mine();if(e.code==='KeyG')place()};window.onkeyup=e=>{if(e.code==='KeyW'||e.code==='KeyS')sy=0;if(e.code==='KeyA'||e.code==='KeyD')sx=0};resize();addEventListener('resize',resize);hotbar()}
function startGame(){document.getElementById('menu').style.display='none';document.getElementById('hud').hidden=false;document.getElementById('loading').style.display='none'}
function boot(){try{setup();gen(seedText);startGame();requestAnimationFrame(loop)}catch(e){document.getElementById('loading').style.display='none';document.getElementById('menu').style.display='none';document.getElementById('error').hidden=false;document.getElementById('errText').textContent=e.stack||e}}
function loop(now){let dt=Math.min((now-last)/1000,.05);last=now;move(dt);draw();saveTimer+=dt;if(saveTimer>20){saveTimer=0;localStorage.setItem('NikitaCraftsSave',JSON.stringify({seedText,world:[...world],p:[px,py,pz],yaw,pitch,selected}))}requestAnimationFrame(loop)}
boot();
})();
